<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join Now</name>
   <tag></tag>
   <elementGuidId>65f7b95f-51bb-466b-a98e-0cd051952175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex.justify-center.items-center.rounded-lg.border.border-gray-200.bg-white.px-3.py-2.text-gray-800</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/main/section/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c94aaa4-30e1-4e52-8fd1-e05aca52f376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://chat.whatsapp.com/Il4a3xL5yJ8CHNpM1GN0D0</value>
      <webElementGuid>a4b9b6b7-59a8-45bb-8107-694d034ce2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>043a11e4-b445-4359-8a2f-9d1f5e58db85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-center items-center rounded-lg border border-gray-200 bg-white px-3 py-2 text-gray-800</value>
      <webElementGuid>e256c244-8a2e-4df1-b132-20574d193740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Join Now</value>
      <webElementGuid>57700ce4-615c-4942-a02c-029aa46427bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;flex items-start&quot;]/main[@class=&quot;overflow-y-hidden relative w-full h-full bg-gray-50 dark:bg-gray-900&quot;]/section[@class=&quot;px-4 pb-4 sm:pb-10 lg:px-20&quot;]/div[@class=&quot;flex flex-col gap-3 rounded-lg bg-white p-4 shadow-sm sm:flex-row sm:justify-between&quot;]/a[@class=&quot;flex justify-center items-center rounded-lg border border-gray-200 bg-white px-3 py-2 text-gray-800&quot;]</value>
      <webElementGuid>8db20b18-9908-4ba3-868d-2ff6b6e410a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/a</value>
      <webElementGuid>59bf26c3-c17f-4386-9c4b-161fa1f411b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Join Now')]</value>
      <webElementGuid>facf59bf-d71f-4c1a-a28d-3a1cf3c3c914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[2]/following::a[1]</value>
      <webElementGuid>1b46f86b-66f4-41c8-b45d-1e0b750275a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[2]/following::a[2]</value>
      <webElementGuid>61502765-0d6a-4493-bf7d-413c2531c847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest'])[1]/preceding::a[1]</value>
      <webElementGuid>6a94d60b-749d-44ab-b500-453b203de2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>98cb9bc7-5a60-4cfc-856a-96e8de957285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Join Now']/parent::*</value>
      <webElementGuid>3f3ed60e-9eee-470e-a754-f88850991400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://chat.whatsapp.com/Il4a3xL5yJ8CHNpM1GN0D0')]</value>
      <webElementGuid>1f648d78-b2d9-44f3-ab87-b14b2dadb33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/a</value>
      <webElementGuid>69d243d1-e435-404e-9ec1-49c477a49c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://chat.whatsapp.com/Il4a3xL5yJ8CHNpM1GN0D0' and (text() = 'Join Now' or . = 'Join Now')]</value>
      <webElementGuid>e5cec7f4-2a07-424e-8fbe-5f11478e1ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
