<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply Filter</name>
   <tag></tag>
   <elementGuidId>2acbc5e6-4e6a-4df0-9385-2c7ba3c46086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apply-filter-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='apply-filter-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c20720b3-61d5-4fec-97a0-06fbf68eefb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bae3a44-a47d-4306-90bc-71c036cc1b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start text-sm cursor-pointer hover:bg-gray-100 focus:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 focus:outline-none dark:hover:text-white dark:focus:bg-gray-600 dark:focus:text-white rounded-lg mr-4 w-auto bg-primary-600 px-3 py-2 text-white</value>
      <webElementGuid>a7f68b62-3680-4150-b703-121c2ab53d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apply-filter-btn</value>
      <webElementGuid>94139293-77fc-4beb-a498-fa750850030b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a3c1244-11de-43ed-a977-70caa5b86674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Filter</value>
      <webElementGuid>146b027d-7c50-4a36-8235-6dd580a6d226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apply-filter-btn&quot;)</value>
      <webElementGuid>31482d77-c970-4730-84b8-71d5738840a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='apply-filter-btn']</value>
      <webElementGuid>6651e007-06c1-4782-a893-4e5f12a2e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter']/div/div[2]/li/button</value>
      <webElementGuid>f144f71d-dc19-44fc-8842-6e08abcb2dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part-Time'])[1]/following::button[1]</value>
      <webElementGuid>557a59a3-47c4-4c11-bb4a-19c17b952b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[1]/following::button[1]</value>
      <webElementGuid>cd61c5c4-11eb-4666-aff8-aefd02d5a642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>fcde90d0-73c9-463a-8b0d-0eb29128625e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expert - Forage &amp; Feed Industry'])[1]/preceding::button[2]</value>
      <webElementGuid>2b22f523-7462-4712-a5ab-cf404abca266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Filter']/parent::*</value>
      <webElementGuid>d16c992a-1999-449b-a270-131a2ea61ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>3aecef19-77f6-4ab6-9227-3f3c89ed898d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'apply-filter-btn' and (text() = 'Apply Filter' or . = 'Apply Filter')]</value>
      <webElementGuid>5eadd355-9b2a-4e2e-b18f-5561c480ec5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
