<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_musahabeebefy10gmail.com_verify3</name>
   <tag></tag>
   <elementGuidId>63e76f28-d0d0-43cb-809a-7ad8608e0da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17fef147-e67b-4e3e-9c51-999b9608ffb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-[57px] max-w-[44px] justify-end rounded-lg border border-gray-200 text-center text-3xl font-extrabold text-gray-900</value>
      <webElementGuid>1052bacc-6dbc-4a7e-9b65-3aabd027cc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_3</value>
      <webElementGuid>32e837a9-6119-438b-a91e-6a23b8d5d047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verify[3]</value>
      <webElementGuid>c68d012e-317d-4052-9ff3-f1023cc0341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77e3489f-3981-433a-8aa0-13bfc829731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7909b643-7fe9-4592-965a-54cec1239b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_3&quot;)</value>
      <webElementGuid>37c924ed-64ce-4d7d-92aa-e0aae7617073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_3']</value>
      <webElementGuid>48e0db66-5d13-455d-98be-41cc7bdbdf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/div[3]/input</value>
      <webElementGuid>69377924-74f6-4839-bc24-b5db344ad0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1f91b334-36db-467e-9b3f-b968f6b78dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verify_3' and @name = 'verify[3]' and @type = 'text']</value>
      <webElementGuid>2711dfc3-c383-469b-a061-122d96ce1e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
