<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Latest Jobs_default-radio-2</name>
   <tag></tag>
   <elementGuidId>2c5b4859-b8fb-4f88-bb17-d724a6a3c0ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#default-radio-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='default-radio-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>499b0fef-134e-4454-9563-28b61f3f4e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default-radio-2</value>
      <webElementGuid>13c4f5f5-70a4-4140-a3b6-123c9e9ff8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5dc5e4d1-3855-4847-8694-c04e63f2c3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>default-radio-2</value>
      <webElementGuid>390b72b7-0ada-4e7d-8bc1-e7a8f7455704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 border-gray-300 bg-gray-100 text-blue-600 focus:ring-2 focus:ring-blue-500 dark:border-gray-500 dark:bg-gray-600 dark:ring-offset-gray-700 dark:focus:ring-blue-600 dark:focus:ring-offset-gray-700</value>
      <webElementGuid>2844e100-8e33-4944-b982-a5980fa9fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-radio-2&quot;)</value>
      <webElementGuid>89f4ec33-4532-4df9-a21e-c5719053ef47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='default-radio-2']</value>
      <webElementGuid>6887b490-7ccb-4822-b143-33f648646c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r2:']/ul/ul/div[2]/div/input</value>
      <webElementGuid>cae969f9-eb36-49f3-b309-6d32775f34e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9df108a2-85ab-4c59-b055-50f319a7c6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'default-radio-2' and @type = 'radio' and @name = 'default-radio-2']</value>
      <webElementGuid>4f19fd89-c132-4e4a-b0e2-256eee64c0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
