<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_musahabeebefy10gmail.com_verify6</name>
   <tag></tag>
   <elementGuidId>6936e8c4-50ec-48ba-a653-54f9094cae9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0aaf51b-6a90-47e8-9810-2537dfbb7283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-[57px] max-w-[44px] justify-end rounded-lg border border-gray-200 text-center text-3xl font-extrabold text-gray-900</value>
      <webElementGuid>fee0232f-60d7-4469-b036-c3e3ffae3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_6</value>
      <webElementGuid>ac111010-c48c-450f-8dfc-2d5006f4f6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verify[6]</value>
      <webElementGuid>d73c8fed-e979-41d3-9887-5d358519d604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81886951-d03e-4795-a929-18951602aed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bc9847d6-83cf-4849-82b0-028a1eadc166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2d5606be-9ee3-44bd-b79f-8f69817c0bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_6&quot;)</value>
      <webElementGuid>91b53624-72a0-477d-b80a-28f723fa2a83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_6']</value>
      <webElementGuid>364f281b-f17b-4886-aef9-28d51add0b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/div[6]/input</value>
      <webElementGuid>609be567-7084-46bb-aeda-dcf9ea78b374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>26ec99db-2989-404b-a70d-9e20e2d496bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verify_6' and @name = 'verify[6]' and @type = 'text']</value>
      <webElementGuid>8b4b6aa5-7181-4691-81a5-bfba822c17e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
