<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_musahabeebefy10gmail.com_verify2</name>
   <tag></tag>
   <elementGuidId>144be48d-518a-4b07-90ce-cf0fac00ba57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3d27cd9-d144-48f7-abfe-153dbd9309ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-[57px] max-w-[44px] justify-end rounded-lg border border-gray-200 text-center text-3xl font-extrabold text-gray-900</value>
      <webElementGuid>bf177210-a16d-4bcd-bcb4-4a810381a2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_2</value>
      <webElementGuid>8da14045-42f1-4ca0-bfda-b34f2fbd63df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verify[2]</value>
      <webElementGuid>80fdf94e-2f67-4db4-bd0b-db4a9d020881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>129b70d0-f849-4817-a2a4-c2329bf991ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d83b0d95-5b07-476b-bdc3-c6dff68fa085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_2&quot;)</value>
      <webElementGuid>62af83c7-1a28-4619-a77f-21ac48a35198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_2']</value>
      <webElementGuid>8aabf1f6-d824-49b8-a9df-f412c9a3e978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/div[2]/input</value>
      <webElementGuid>39c28049-e47a-43fe-8699-d8eb1b5ca715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>82c86ac3-e130-421a-b879-9d4be5a20524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verify_2' and @name = 'verify[2]' and @type = 'text']</value>
      <webElementGuid>d3492b24-b83c-44e0-ac99-a0d3e18c7d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
