<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old_default-radio-2</name>
   <tag></tag>
   <elementGuidId>828dcb6f-f361-4493-8b74-8a02c1347d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#default-radio-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='default-radio-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45166c15-d8ed-4f9c-876c-4eaf3c0b7b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default-radio-1</value>
      <webElementGuid>6b28fce9-34f4-4d8f-90f5-296208cb18cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6d820a99-b47f-4893-af54-c9bd38515f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>default-radio-2</value>
      <webElementGuid>1aec11d6-df89-4afb-b80b-39a5e33c78c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 border-gray-300 bg-gray-100 text-blue-600 focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>40acaaa2-753e-4b3e-8d69-7fc420f07a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-radio-1&quot;)</value>
      <webElementGuid>46f94b3a-dc54-456b-83f6-01f4cb742813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='default-radio-1']</value>
      <webElementGuid>1480713d-cf44-49dd-8e54-2e28e1743a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r2:']/ul/ul/div/div/input</value>
      <webElementGuid>d2f08d4f-4b81-4180-a994-ba00a17b7994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dba8366d-5e1e-49b6-83c2-f74995bd9cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'default-radio-1' and @type = 'radio' and @name = 'default-radio-2']</value>
      <webElementGuid>99c34a57-1a19-4a14-b25d-3b11c7df9817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
