<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_musahabeebefy10gmail.com_verify1</name>
   <tag></tag>
   <elementGuidId>40aebfad-ff3c-4f44-8b98-2540b275d04e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>287938fe-11d1-459d-8951-4fcaae7cb599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-[57px] max-w-[44px] justify-end rounded-lg border border-gray-200 text-center text-3xl font-extrabold text-gray-900</value>
      <webElementGuid>00cbeb05-84ec-4480-a008-0a63941c7ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_1</value>
      <webElementGuid>24681daa-52b0-44c0-bfcd-d8593e348e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verify[1]</value>
      <webElementGuid>f92201a6-77e0-4ab5-9128-1bd2c8c3f037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fae29db-c0f9-401c-b323-46fb52daa236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6eae87bc-f561-4638-ba0a-f2f3bbec3b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_1&quot;)</value>
      <webElementGuid>80a9a029-2978-4167-85fc-64f26c3e4b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_1']</value>
      <webElementGuid>4dd6c630-0729-44f4-9338-41bf6440d951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>ee817f39-3b5e-4a48-88bc-b4111cc85a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e1bfecee-a549-490d-a637-aa4a3315593b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verify_1' and @name = 'verify[1]' and @type = 'text']</value>
      <webElementGuid>bd8985c5-9c6f-47a6-a0d8-90a940cebf0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
