<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_musahabeebefy10gmail.com_verify4</name>
   <tag></tag>
   <elementGuidId>b4b8d054-b641-40db-8772-249a26ecf65c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af8fb487-92cf-4344-9899-13e0e6ffbc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-[57px] max-w-[44px] justify-end rounded-lg border border-gray-200 text-center text-3xl font-extrabold text-gray-900</value>
      <webElementGuid>f2eac9ef-2b86-4080-8b21-1640fb8ba46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_4</value>
      <webElementGuid>0763621a-fbcc-4ae9-bbe1-a3dff8767154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verify[4]</value>
      <webElementGuid>37627005-25e7-4a28-9639-6a2fd86df664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f81aa737-5d69-437f-b36c-3286ba85b89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1cbd391-6953-4c5f-9143-bb6ed6bb3252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_4&quot;)</value>
      <webElementGuid>1b27060a-c3b8-485e-8b82-3328cf27fd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_4']</value>
      <webElementGuid>f8d85131-83a0-4c89-8114-69a182621ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/div[4]/input</value>
      <webElementGuid>11ae7aaf-b209-4f4f-86fd-5aacaf98f04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d40efab8-d8fd-4fbd-b300-bada937d34b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verify_4' and @name = 'verify[4]' and @type = 'text']</value>
      <webElementGuid>22b33884-5628-4aa1-94c5-a6e78799a9d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
