<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_On-site</name>
   <tag></tag>
   <elementGuidId>788ff8b6-a5e0-4c6e-a7c7-53b6ae3b1d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter']/div/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6577cd2c-26f1-4a09-9f4a-244d8869c159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>onsite-option</value>
      <webElementGuid>edb57af1-2bb9-4648-9ec3-2a537be75eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center w-full px-5 py-2 text-gray-500 bg-gray-100 border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:text-primary-600 peer-checked:border-blue-600 hover:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700</value>
      <webElementGuid>50116dca-3be8-49af-bc4c-d28ad843ab6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On-site</value>
      <webElementGuid>3d325981-243a-4c43-86e7-cd375d3b01b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter&quot;)/div[@class=&quot;flex flex-col gap-6 pl-0&quot;]/div[@class=&quot;grid grid-cols-2 gap-3&quot;]/div[2]/label[@class=&quot;inline-flex items-center justify-center w-full px-5 py-2 text-gray-500 bg-gray-100 border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:text-primary-600 peer-checked:border-blue-600 hover:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700&quot;]</value>
      <webElementGuid>f8251287-bf6f-4113-8909-f914b5aab614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter']/div/div/div[2]/label</value>
      <webElementGuid>4ec13c29-52c7-46aa-9a99-c4d84b722d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote'])[1]/following::label[1]</value>
      <webElementGuid>6430188f-785d-410f-bfb2-c7459a9e8abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::label[2]</value>
      <webElementGuid>c5fe523e-3abf-43ff-8c23-66baf7f4237b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[1]/preceding::label[1]</value>
      <webElementGuid>953947a3-77b4-47f2-84f1-aa2719e7fa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part-Time'])[1]/preceding::label[2]</value>
      <webElementGuid>c3775ebd-8729-4646-963c-ee35959d702f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On-site']/parent::*</value>
      <webElementGuid>519d654a-4c61-4d22-9e63-c09a75c087c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>5cd54775-58d7-4f63-a0c0-dad6c1fd969a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'On-site' or . = 'On-site')]</value>
      <webElementGuid>ef4af220-890b-49bf-9992-151b186ca9d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
