<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login with email</name>
   <tag></tag>
   <elementGuidId>dc70bc42-8e0e-45de-975b-1cc921f78212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex.items-stretch.transition-all.duration-200.rounded-md.text-sm.px-3.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/form/div[4]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d610b93-197a-49df-8988-1befa6f53779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-stretch transition-all duration-200 rounded-md text-sm px-3 py-2</value>
      <webElementGuid>5e45a825-e25e-40d1-8c85-6a6dd0cb854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login with email</value>
      <webElementGuid>3ccad03d-cbba-4561-8d52-cd921b9037cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex flex-col items-center justify-center px-6 lg:min-h-screen lg:flex-row lg:gap-10 lg:gap-y-12 lg:px-16&quot;]/div[@class=&quot;flex rounded-lg border border-gray-200 bg-white shadow-md dark:border-gray-700 dark:bg-gray-800 flex-col md:max-w-xl md:flex-row w-full md:[&amp;>*]:w-full md:[&amp;>*]:p-16 [&amp;>img]:hidden md:[&amp;>img]:w-96 md:[&amp;>img]:p-0 lg:[&amp;>img]:block&quot;]/div[@class=&quot;flex h-full flex-col justify-center gap-4 p-6&quot;]/form[1]/div[@class=&quot;mb-6&quot;]/button[@class=&quot;group flex h-min items-center justify-center p-0.5 text-center font-medium relative focus:z-10 focus:outline-none text-white border border-transparent enabled:hover:bg-cyan-800 focus:ring-cyan-300 dark:bg-cyan-600 dark:enabled:hover:bg-cyan-700 dark:focus:ring-cyan-800 rounded-lg focus:ring-2 w-full bg-primary-700&quot;]/span[@class=&quot;flex items-stretch transition-all duration-200 rounded-md text-sm px-3 py-2&quot;]</value>
      <webElementGuid>de6531ed-8cae-46ac-bee7-a48e3f4edcc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/form/div[4]/button/span</value>
      <webElementGuid>5d0a17d6-6ef0-4318-803e-4f552cef15c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::span[1]</value>
      <webElementGuid>2b5efcb6-b731-4407-9bca-ccf95fbc5d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::span[1]</value>
      <webElementGuid>7fabcca7-564e-49bf-bbc9-4d5e537c6656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::span[1]</value>
      <webElementGuid>42478a53-e22d-4ba1-963f-7224d3b0099a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login with email']/parent::*</value>
      <webElementGuid>6dc5d5f8-c74d-44a0-8459-073f0679cad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>9cda4ec9-79bb-416b-ba80-b6f5e3b744a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login with email' or . = 'Login with email')]</value>
      <webElementGuid>d5b02086-7894-4f18-bfac-2979b6742244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/button/span</value>
      <webElementGuid>5a901299-4e0c-4a26-bc45-3767fb602a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::span[1]</value>
      <webElementGuid>91087dbb-e0d1-4ee7-9b5e-7bc852c82941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with Google'])[1]/following::span[1]</value>
      <webElementGuid>af63d0bb-094e-46f5-b201-337ea9aa9c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
