<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Financial Modeling</name>
   <tag></tag>
   <elementGuidId>72b24f38-2fcd-45a3-8ba5-42abd9896fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[5]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > div.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ac1ab05-013e-4398-87ec-110c106778a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>18886f81-9cfc-4af0-9edd-379a38dfee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Financial Modeling</value>
      <webElementGuid>14636382-9fab-4e23-80d2-33998919caee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[5]/div[@class=&quot;horizontal-slider&quot;]/div[@class=&quot;slides-cont&quot;]/div[3]/div[@class=&quot;pointer&quot;]</value>
      <webElementGuid>f83d9344-078f-430d-836c-77e0db99c15f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[5]/div/div/div[3]/div</value>
      <webElementGuid>0674072c-ab7d-4d48-a6e4-e1060eb4b946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Presentation'])[1]/following::div[2]</value>
      <webElementGuid>36e236c1-c7e9-4e89-911f-3fc64eb88a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap Table Simulation'])[1]/following::div[4]</value>
      <webElementGuid>4ec8e70a-1489-4507-a8ce-46fc797b4748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go-To-Market Strategy'])[1]/preceding::div[1]</value>
      <webElementGuid>bc9d136f-b002-4195-a51c-dfb34e674aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]/div/div/div[3]/div</value>
      <webElementGuid>86c4432b-7a99-4c24-b1ec-7868ebf320a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Financial Modeling' or . = 'Financial Modeling')]</value>
      <webElementGuid>55914d18-288d-4670-800b-d818c403ade4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
