<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Investor Presentation</name>
   <tag></tag>
   <elementGuidId>ec9e7dd1-10b4-42db-9334-7d66f7b90cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[5]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86f6e371-08fa-4882-acb8-c0ad554fa1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>3b01bc44-0bba-474a-9ffd-79d0606f0869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investor Presentation</value>
      <webElementGuid>ae068a68-b5f0-4c2c-a7c2-23520ada1f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[5]/div[@class=&quot;horizontal-slider&quot;]/div[@class=&quot;slides-cont&quot;]/div[2]/div[@class=&quot;pointer&quot;]</value>
      <webElementGuid>479b1273-3af1-4ff3-b9e1-3677c8cdee4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[5]/div/div/div[2]/div</value>
      <webElementGuid>3c978964-0e06-4bbd-860a-551b63a10c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap Table Simulation'])[1]/following::div[2]</value>
      <webElementGuid>d4069ee2-ee48-49aa-b219-f4d8bff557c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='common requests'])[1]/following::div[7]</value>
      <webElementGuid>3dde30c8-07c5-418c-883f-ec3c57afc569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Modeling'])[1]/preceding::div[1]</value>
      <webElementGuid>8593e85f-ad25-4995-aa02-5ce24e5cb2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]/div/div/div[2]/div</value>
      <webElementGuid>bab9b978-9415-4f17-976e-f5fe6b789502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Investor Presentation' or . = 'Investor Presentation')]</value>
      <webElementGuid>6cc532cd-b011-4718-b543-ae55e5be6aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
