<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Build afuturewhereglobal, top tier, ind_634686</name>
   <tag></tag>
   <elementGuidId>5fece589-ee3c-4eab-9cfc-22e7ff8262dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mc-heading-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6e82ff1-5e10-4a12-a1a0-0d00d4514924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mc-heading-component</value>
      <webElementGuid>c6a41fa3-e111-401b-a044-c0ee51481d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Build afuturewhereglobal, top tier, independent talentempowerseveryorganization</value>
      <webElementGuid>7225cca0-dad0-4e25-ad14-38b201a24379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[1]/div[@class=&quot;mc-heading-component&quot;]</value>
      <webElementGuid>e8797e12-cd3d-4e1c-9f42-a30bd0811b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>1e5fb917-ea84-4755-aa31-6b2f85c4cc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[2]/following::div[4]</value>
      <webElementGuid>abc39102-02d2-4311-940e-05d160fa73e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/following::div[12]</value>
      <webElementGuid>7ac78b78-2303-4ab0-b204-e01b7d7e6a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>f52d5c2a-2231-41ac-9943-f5990646da2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Build afuturewhereglobal, top tier, independent talentempowerseveryorganization' or . = 'Build afuturewhereglobal, top tier, independent talentempowerseveryorganization')]</value>
      <webElementGuid>f836b9ba-1b09-432c-ad16-519e7b3189b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
