<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Corporations</name>
   <tag></tag>
   <elementGuidId>793d8d4b-35df-4e9d-844c-4333b42dbd49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[2]/div[2]/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > div.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c07cb50-fda3-4368-8880-26ecfc36920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>e7a3f37b-379f-4b53-b3e4-2315157a65e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporations </value>
      <webElementGuid>a1fb39b4-a3fc-4f4d-a2d7-e3630a6314c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[2]/div[2]/div[4]/div[@class=&quot;pointer&quot;]</value>
      <webElementGuid>a17e5931-c3c0-4cc7-904e-ab2a80f8a88a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div[2]/div[2]/div[4]/div</value>
      <webElementGuid>d04915f3-5a25-4e0d-bb70-6f83f6184d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clientele'])[1]/following::div[9]</value>
      <webElementGuid>de7b4134-d330-4614-b5f4-daec2d6c8c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='in Our'])[1]/following::div[9]</value>
      <webElementGuid>f76b279a-c58d-4844-9a96-cbec55a47ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fostering effective partnerships with VCs and PEs'])[1]/preceding::div[5]</value>
      <webElementGuid>bc799102-31ac-455b-9e00-050b8ed61e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accelerate Project Success:'])[1]/preceding::div[11]</value>
      <webElementGuid>f607e056-d0c3-4ed0-a251-fe025971be72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[4]/div</value>
      <webElementGuid>40377b31-dc6c-4ca5-bed9-4dbba72a9068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Corporations ' or . = 'Corporations ')]</value>
      <webElementGuid>747609a5-373c-4c6e-adf6-ae9c29bc36f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
