<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Revolutionizing Last-Mile Logistics by F_0c028f</name>
   <tag></tag>
   <elementGuidId>95872d27-4a58-4269-b962-06f44ea94ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/a/div/div/div/div[2]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6d991155-c32b-4ccf-8b62-7410d6e3e162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Revolutionizing Last-Mile Logistics by Facilitating a Public-Postal Service's Journey through Digital Transformation </value>
      <webElementGuid>5b0e1c8c-31ed-4ff6-bc6a-bf50d8dab617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6&quot;]/a[1]/div[1]/div[1]/div[1]/div[2]/h3[1]</value>
      <webElementGuid>44ba4f5a-51a7-4925-87ba-8a1c5178080e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/a/div/div/div/div[2]/h3</value>
      <webElementGuid>37616e4d-f6e2-4341-9f00-60433d194ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empowering Educational Excellence by Transforming Abu Dhabi’s Academic Landscape'])[1]/following::h3[1]</value>
      <webElementGuid>4cba7bb7-f0c6-4abb-b85a-73c35ea41734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read Case Study'])[1]/following::h3[2]</value>
      <webElementGuid>6f0411cd-8af2-4ac5-8c4e-05daea4a3428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empowering Early Childhood Development Initiatives for a Brighter Future in UAE'])[1]/preceding::h3[1]</value>
      <webElementGuid>2624b288-5354-49ed-aed7-656ef031b14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accelerating Technological Innovation and Entrepreneurship in Abu Dhabi'])[1]/preceding::h3[2]</value>
      <webElementGuid>64a32f3b-fa9c-4fb3-a45b-4c15537eacae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/div/div[2]/h3</value>
      <webElementGuid>fae174f4-037e-4b0a-b16a-2a11065a944d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = concat(&quot;Revolutionizing Last-Mile Logistics by Facilitating a Public-Postal Service&quot; , &quot;'&quot; , &quot;s Journey through Digital Transformation &quot;) or . = concat(&quot;Revolutionizing Last-Mile Logistics by Facilitating a Public-Postal Service&quot; , &quot;'&quot; , &quot;s Journey through Digital Transformation &quot;))]</value>
      <webElementGuid>2407e364-308f-48b0-ad11-b8e89d9c7db2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
