<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Agriculture</name>
   <tag></tag>
   <elementGuidId>91284b64-d2f2-4c05-8650-a874c8ab4e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[4]/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > div.pointer > h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>64248bd3-00db-4b4a-ae4a-44bd03316416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agriculture</value>
      <webElementGuid>9d847555-b923-4929-a8f1-5c771d566882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[1]/div[4]/div[@class=&quot;pointer&quot;]/h5[1]</value>
      <webElementGuid>d3a681a9-1df0-463e-a57a-ca9d38edfe77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[4]/div/h5</value>
      <webElementGuid>f5c5d736-47c0-419e-b0fb-53cba3f4dfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::h5[1]</value>
      <webElementGuid>888e173a-3964-4e5d-9b1f-97c31da5768a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public sector'])[1]/following::h5[2]</value>
      <webElementGuid>f513af3d-4454-441d-8965-367977b9c47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::h5[1]</value>
      <webElementGuid>c113761a-dd20-403e-89c9-d9cba8eadf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistics'])[1]/preceding::h5[2]</value>
      <webElementGuid>4db60909-5ac1-41c6-b93a-22f6d947d9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agriculture']/parent::*</value>
      <webElementGuid>d67593b8-d89f-45ca-a589-56dcadddc983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h5</value>
      <webElementGuid>251f2e99-fe34-47ee-bc41-0d00ba8954ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Agriculture' or . = 'Agriculture')]</value>
      <webElementGuid>babcb8bd-3326-43e6-b280-a79fd2051fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
