<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Education</name>
   <tag></tag>
   <elementGuidId>31264b94-0bb6-4c98-93bd-974b2c043c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[3]/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > div.pointer > h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>a4d8ea3e-9595-4abd-80a2-aacc08e44dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>581cd706-32df-440a-97f1-24c0a9acd8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[1]/div[3]/div[@class=&quot;pointer&quot;]/h5[1]</value>
      <webElementGuid>493cbd39-fc82-45b1-a137-a3c322525e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[3]/div/h5</value>
      <webElementGuid>51ea977a-b542-41c6-a053-4fda6d2c4c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public sector'])[1]/following::h5[1]</value>
      <webElementGuid>ee7e1395-72f7-4976-91de-edcebbaf8205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Case Studies'])[1]/following::h5[2]</value>
      <webElementGuid>4bdf27f4-e93f-401d-983f-ec650bb16ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agriculture'])[1]/preceding::h5[1]</value>
      <webElementGuid>d6a09524-7d70-43a1-84d1-5325d52844fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::h5[2]</value>
      <webElementGuid>82c6d33c-21c7-4cbb-bcc6-c80ca13a453b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Education']/parent::*</value>
      <webElementGuid>e0bb3cdb-0ffe-4de7-a317-513a70521796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h5</value>
      <webElementGuid>394c55db-0003-4206-9cf2-bf2136ecc747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>87424e3a-dff4-4293-aa11-4f53e502598b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
