<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Logistics</name>
   <tag></tag>
   <elementGuidId>c04a9d4c-9c5c-473e-bc32-bba3d4d51317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[6]/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(6) > div.pointer > h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>011a318a-d294-4068-8382-36de6db19a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logistics</value>
      <webElementGuid>eb3c7552-cfe4-4925-a73a-2643d2f166c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[1]/div[6]/div[@class=&quot;pointer&quot;]/h5[1]</value>
      <webElementGuid>f6d58a58-bdcc-45c7-8add-edca5d6af5cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[6]/div/h5</value>
      <webElementGuid>12027093-f316-4105-a912-ad6917ef60f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/following::h5[1]</value>
      <webElementGuid>d70d39dc-d482-4de5-b5ae-fb45baba9753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agriculture'])[1]/following::h5[2]</value>
      <webElementGuid>093c54ca-5f55-4d65-b58a-7b0d23df3df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover the ways in which we have assisted brands achieve success.'])[1]/preceding::h5[1]</value>
      <webElementGuid>134644b0-2cfa-4098-943d-6ed47f870eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovating Bioacoustic Technology to Enhance Environmental Conservation Efforts'])[1]/preceding::h5[1]</value>
      <webElementGuid>4eed9a2c-27cd-4433-ad29-7876017c12af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logistics']/parent::*</value>
      <webElementGuid>49ba7b78-1776-4195-82cb-97161c220aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/h5</value>
      <webElementGuid>474badba-ed5b-401a-87eb-b897b9fefb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Logistics' or . = 'Logistics')]</value>
      <webElementGuid>631a4571-7def-459f-b9e5-27a7b79b6ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
