<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>49d5b12a-6a04-466a-b0c2-8295ccffe149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-12.col-md-6.cols-lg-6 > div > div.img-cont.img-loaded > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08f0a201-ef68-4045-a685-a9aaaa77121d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ac.wbcdn.in/cache/erp/37/1kb8cp-Group1399_w450_.png</value>
      <webElementGuid>b856220c-7357-4d9c-8f99-0d9e5a2b514b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-6 cols-lg-6&quot;]/div[1]/div[@class=&quot;img-cont  img-loaded&quot;]/img[1]</value>
      <webElementGuid>beda4923-63f6-4d45-8fe8-d1f39ab0bef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div[2]/div/div/img</value>
      <webElementGuid>a8a6b675-631c-40b6-b524-58ede734f436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/1kb8cp-Group1399_w450_.png')]</value>
      <webElementGuid>06a9048d-6c30-4f36-892c-50f938d1996d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/img</value>
      <webElementGuid>ab854ff6-3e47-4aac-95a3-cef50752040d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/1kb8cp-Group1399_w450_.png']</value>
      <webElementGuid>1224f4e9-c999-4d28-97dc-441452c5b3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/1k1odc-Group1396_w450_.png')]</value>
      <webElementGuid>2d06e153-7542-4f68-892b-fca9ed5843de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/1k1odc-Group1396_w450_.png']</value>
      <webElementGuid>2ac24b5b-adbf-4a6a-86f4-7fcf4e5e4da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div/div[2]/div/div/img</value>
      <webElementGuid>8eb11d4b-c5d6-4188-853f-0a8371ca7729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/1m8mup-Frame3234921_w450,h501_.png')]</value>
      <webElementGuid>4333cc14-4838-4233-a013-9107ae2e4d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/img</value>
      <webElementGuid>9a8afa4e-48ae-49a3-99df-73fc265d2782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/1m8mup-Frame3234921_w450,h501_.png']</value>
      <webElementGuid>e9df978c-c4bd-47f2-ab9c-3429f0bd1ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div/div/div/div/div/a/div/div/img</value>
      <webElementGuid>dcb7fa1c-706b-4e2f-9e39-4e77985459da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/wbac-main/erp/37/199k4o-Logo.svg')]</value>
      <webElementGuid>2ba3af94-66b6-47ed-a007-d9faca9d0e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7b5d6e86-d5d1-41d7-87ee-19bc42aec590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/wbac-main/erp/37/199k4o-Logo.svg']</value>
      <webElementGuid>189684aa-a1fb-4dbb-aa48-097faf5f923b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
