<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3</name>
   <tag></tag>
   <elementGuidId>4a306d0e-c874-4f3e-a1a1-c4fb2c3dd639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/a/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0efb0982-b66a-4ac3-9d99-5c839319353d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ac.wbcdn.in/cache/erp/37/jgf37-postalservice_w300,h346_.jpg</value>
      <webElementGuid>4b6e11fd-57ca-46c7-94f7-fc93a1c9fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6&quot;]/a[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;img-cont rounded-img img-loaded&quot;]/img[1]</value>
      <webElementGuid>ae5c99e8-54ce-4929-a8ae-7ba659cc5158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/a/div/div/div/div/div/img</value>
      <webElementGuid>7f00da87-68b5-4dde-beb4-065d69110bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/jgf37-postalservice_w300,h346_.jpg')]</value>
      <webElementGuid>fadddbfb-1cf7-4f2b-a246-2f1e40def640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/div/div/div/img</value>
      <webElementGuid>3457a229-7281-4cfa-a40d-b2c57c173afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/jgf37-postalservice_w300,h346_.jpg']</value>
      <webElementGuid>2eeafdd6-2715-4ca0-89a5-b2a89c114563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
