<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>dabecc89-01e4-4434-9ec8-44e6b8acdeb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[3]/a/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>504eb12f-d3d7-4bf6-9bab-366f30380f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg</value>
      <webElementGuid>eba207dc-98c8-4691-bf97-17497c537a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6&quot;]/a[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;img-cont rounded-img img-loaded&quot;]/img[1]</value>
      <webElementGuid>3863fed2-6e4f-4d7d-924b-1567bda843a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[3]/a/div/div/div/div/div/img</value>
      <webElementGuid>430fb18d-483c-490b-9ffb-14777d0850a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg')]</value>
      <webElementGuid>1c12e0ac-6a6e-47c0-b125-d210dc4163e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/div/div/div/img</value>
      <webElementGuid>be1be9ff-e333-48c9-972e-4275dad37ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg']</value>
      <webElementGuid>3c7769c2-550b-4884-96a3-55cd9fb4f390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div/a/div/div/div/div/div/img</value>
      <webElementGuid>fe0390e4-14fb-485e-96e8-39fe02875107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/62crp-youngstudentstakingselfie232148522226_w300,h346_.jpg')]</value>
      <webElementGuid>308786c0-6b79-401d-8c95-9b6d186852a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/div/div/div/div/img</value>
      <webElementGuid>ebb13e48-f2d5-41db-a4c1-080a39844cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/62crp-youngstudentstakingselfie232148522226_w300,h346_.jpg']</value>
      <webElementGuid>8138d25b-a783-4c2b-9369-5b03c80b4352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
