<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>e4f53da5-a3e2-431b-ba64-a923d963f6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[3]/a/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9b6116ed-2e44-4a86-825b-0921c7fdcc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg</value>
      <webElementGuid>50d07a80-7908-495a-aeaa-e4b8f6f1913b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[3]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6&quot;]/a[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;img-cont rounded-img img-loaded&quot;]/img[1]</value>
      <webElementGuid>579a6d59-012f-4d2f-8f96-360043a91ed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div[3]/a/div/div/div/div/div/img</value>
      <webElementGuid>3c4099c8-fcf1-4351-a234-f9b408b72aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg')]</value>
      <webElementGuid>31e69dcb-982c-4949-8af9-2e59f0d3484c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/div/div/div/img</value>
      <webElementGuid>231decee-53c9-43b7-b397-33891bdf094f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ac.wbcdn.in/cache/erp/37/jb1m1-diversekidsreadingbooks53876146406_w300,h346_.jpg']</value>
      <webElementGuid>c64acc7c-a530-4231-b0c4-a2e90f4ca968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
