<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Our service package offerings comprehensi_ba124d</name>
   <tag></tag>
   <elementGuidId>981c6e65-75da-48f1-9340-4c4536df747b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>639083f0-5848-4bef-9733-012edfad013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our service package offerings comprehensively covers large institutions’ as well as early stage ventures' and startups requirements to cater towards well-defined problem statements.</value>
      <webElementGuid>c4b4bc59-1d3c-4868-bd5e-32f46c93c450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-6 cols-lg-6&quot;]/div[1]/div[1]/p[1]</value>
      <webElementGuid>996e1816-3433-4412-b151-fef49b28ecff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div/div/p</value>
      <webElementGuid>977e6ea1-1149-4406-8986-6f33392c6978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Packages'])[1]/following::p[1]</value>
      <webElementGuid>148cc076-028e-44d6-95d1-d67eea2c1c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[2]/following::p[1]</value>
      <webElementGuid>10a3e739-ac97-49b3-a2c7-e02b8bd18fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Our Solutions'])[1]/preceding::p[1]</value>
      <webElementGuid>7b101e8d-261e-4a71-a962-4a85decc5171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted'])[1]/preceding::p[1]</value>
      <webElementGuid>b752e161-178e-4ed4-9288-cbd86138db60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>4d469ff1-5021-4612-95e1-da0228a6700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;Our service package offerings comprehensively covers large institutions’ as well as early stage ventures&quot; , &quot;'&quot; , &quot; and startups requirements to cater towards well-defined problem statements.&quot;) or . = concat(&quot;Our service package offerings comprehensively covers large institutions’ as well as early stage ventures&quot; , &quot;'&quot; , &quot; and startups requirements to cater towards well-defined problem statements.&quot;))]</value>
      <webElementGuid>4e370163-7c38-4830-a0ee-66d146cd2a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
