<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OpportunitiesResourcesCase StudiesOnboa_d9b986</name>
   <tag></tag>
   <elementGuidId>512de7fb-72b7-4d70-86d9-444a4c7961eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.visible-only-desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38746fd3-4715-45c2-af13-a035410eaf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> visible-only-desktop</value>
      <webElementGuid>fe8becb4-600c-485a-b7ac-a8de747cfbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OpportunitiesResourcesCase StudiesOnboard TalentLoginGet Started</value>
      <webElementGuid>7233cc4c-e1cd-408b-bf6b-bdb916bda794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[1]/div[1]/div[1]/div[@class=&quot;visible-only-desktop&quot;]</value>
      <webElementGuid>7a6862dd-e945-4dc6-8e54-13b40471f4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>aaa8fc78-1d67-4773-967e-4957026dd672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>d032279a-122e-465d-baf5-0cbfbc9763a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OpportunitiesResourcesCase StudiesOnboard TalentLoginGet Started' or . = 'OpportunitiesResourcesCase StudiesOnboard TalentLoginGet Started')]</value>
      <webElementGuid>b4182b6a-3f7f-407f-a679-f2ebd0d0a5f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
