<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Services_loading-mask</name>
   <tag></tag>
   <elementGuidId>5c229e36-efc6-4c52-b2ce-da882663ecd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.loading-mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae79486b-317c-4693-8f0e-cb825af7a593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading-mask</value>
      <webElementGuid>3ff2cb6f-9ac8-492a-bad5-f6b3470075ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[@class=&quot;loading&quot;]/div[@class=&quot;loading-mask&quot;]</value>
      <webElementGuid>b9133fcb-1764-4438-a160-12890b3202d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div</value>
      <webElementGuid>67705eeb-023f-410d-a2a8-ff1a616a2c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>84ed2d54-bbe0-4e77-8611-6e4becae8846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
