<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>92ccc7f1-7e0e-45fb-921e-a5d16410b4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ef3a2d9-7c88-45ae-b25e-38915c4368b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>afcfd016-bf62-494c-8639-c5aa9bd7fa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[2]/div[2]/button[2]</value>
      <webElementGuid>f5113607-bd34-488e-92ab-b87cf7c8a083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>65373ff4-dc66-4287-984e-f71e5c0807bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/following::button[1]</value>
      <webElementGuid>93aef66b-0a42-44e5-b00f-e073b45a8ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::button[2]</value>
      <webElementGuid>6c9e2b82-6bf5-4839-b64a-6da7f207e25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted'])[1]/preceding::button[1]</value>
      <webElementGuid>7c705c40-b4d2-4d12-b675-3426f42a4620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>ef1875fc-f125-42ab-92d3-dbff9fda80b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>1caaea51-e606-47f5-9318-743a95558b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>9054d678-c2ca-471f-b27a-9e41b729432c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
