<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_number_ciid</name>
   <tag></tag>
   <elementGuidId>7339f7e2-38b0-48a7-84e4-3720d1a8a657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>071e66a5-1c1d-4660-a901-9390aca16285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_ciid</value>
      <webElementGuid>6999d674-714a-42d3-a663-c9b9cc94e489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>c65020fe-be70-406b-b2ad-72939c3e0821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234567890</value>
      <webElementGuid>5ed3c3c8-7ab8-454a-8b85-84f9fc0c9fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_ciid&quot;)</value>
      <webElementGuid>988dcbb5-b55a-49a6-ad20-6ee9fb607134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number_ciid']</value>
      <webElementGuid>b8042b0b-82f4-44b8-b732-e9e0aada1915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div/div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>454fe95c-093c-4174-9643-7530d37791d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>fd6b0d85-722e-4c64-89f7-034a7a357172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number_ciid' and @type = 'TEXT' and @placeholder = '1234567890']</value>
      <webElementGuid>1c00c7e5-6f39-41a0-9ff9-270bb00fd69f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
