<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__role_ciid</name>
   <tag></tag>
   <elementGuidId>618974b0-9605-4a97-a0dd-3177de4e3bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#role_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='role_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7e195c0-0673-49ef-89a3-da77e36c9079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role_ciid</value>
      <webElementGuid>15394050-1d62-473b-87de-2d645a39103a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f68133ce-d001-40d0-9648-f60504aa0fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>0f62f62d-bf1a-45c1-912f-9ea03f0a50d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role_ciid&quot;)</value>
      <webElementGuid>c54f86de-0282-495c-ae13-d6526a75164f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='role_ciid']</value>
      <webElementGuid>f57372f3-584f-4efc-af8d-145e1ed63014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>8154e32c-f490-498f-9c3c-639b6d471ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>18f61b82-86ca-4e95-975f-75d9b7312365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'role_ciid' and @type = 'TEXT' and @placeholder = 'Role']</value>
      <webElementGuid>f6ff104e-8232-4ae3-92be-b4fd963a48e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
