<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Name_contact_name_ciid</name>
   <tag></tag>
   <elementGuidId>5cc7f4f8-887d-4112-a3b9-d7e114082aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact_name_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact_name_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc301505-9026-4f7f-98cf-e60137c3fc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact_name_ciid</value>
      <webElementGuid>8edb3b29-9ffe-4614-a6f6-6ab1395ed06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>65445f6b-93c3-4e48-a834-a46d22fe7abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your full name</value>
      <webElementGuid>31c96f32-95bc-4ad8-b8d7-d3ae74d36418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_name_ciid&quot;)</value>
      <webElementGuid>428e1404-034a-4331-a39e-da213c787e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact_name_ciid']</value>
      <webElementGuid>f45766d9-5e05-46a8-a1d2-397b0f25cc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>b0ea14a9-473f-460e-95bc-2a0ec3229dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>7894c54a-abdb-4461-98ae-324cbf295654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact_name_ciid' and @type = 'TEXT' and @placeholder = 'Enter your full name']</value>
      <webElementGuid>2d2a33d4-7db5-4bf3-bbab-b7ef77e8fe44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
