<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duration_qty_ciid</name>
   <tag></tag>
   <elementGuidId>9b8d8a8d-2ed7-439c-b030-d48ca0175715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a04dfd16-5afa-4024-883b-0da4e599038b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty_ciid</value>
      <webElementGuid>38468e2f-1bc7-4835-86ad-254f50ad2574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>0385a0f4-5c1c-4856-aad7-18c91dc561fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty_ciid&quot;)</value>
      <webElementGuid>1469ebf3-0c58-45e6-b8ac-09fecbb7ea49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty_ciid']</value>
      <webElementGuid>8d541127-9a5c-4f56-88bb-24df974851aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[7]/div/div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>2b5d22c3-e694-4de4-96a6-f9934fcd235a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>5e9acb45-d4d2-4e9e-8a47-3d20cd8da2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qty_ciid' and @type = 'TEXT']</value>
      <webElementGuid>1151e463-d573-43fe-8b36-881679006d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
