<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_company_name_ciid</name>
   <tag></tag>
   <elementGuidId>74398af7-91d3-431a-a948-b1af0983e412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_name_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_name_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0dd3745-e309-4037-b3e4-f31c255fd341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_name_ciid</value>
      <webElementGuid>110b21f1-86e6-44a1-915b-38f2ec5a8d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>4d7b56f1-bd00-48f3-a2df-3a842e9f9664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>eg. StrategyConnect</value>
      <webElementGuid>994df7df-6707-41b6-813c-171806835cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_name_ciid&quot;)</value>
      <webElementGuid>7d6273d2-eb02-4369-9744-dd954a68269d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_name_ciid']</value>
      <webElementGuid>31ff4ff8-c174-4441-bdfd-30df3a81a418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>6957295e-6740-4ac4-b259-a3fc840ae3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>51db86c2-85be-4a32-bd19-f313f5987a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'company_name_ciid' and @type = 'TEXT' and @placeholder = 'eg. StrategyConnect']</value>
      <webElementGuid>900ec487-17d2-49b6-b128-17191f0808d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
