<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email_ciid</name>
   <tag></tag>
   <elementGuidId>dfb4de84-6bd2-44c0-b351-535d7a28d3b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>684aad5e-dd6a-44e4-9bda-f028121bfff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_ciid</value>
      <webElementGuid>067bb477-4886-4265-90de-1baa37d3f0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>ae603df9-ada1-4e86-88b0-3b49bfffaf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@example.com</value>
      <webElementGuid>9db93c80-ae97-452d-af8d-7de4751c7918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_ciid&quot;)</value>
      <webElementGuid>a5d5bb19-a5c9-409e-b2c8-8dcc663f0c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_ciid']</value>
      <webElementGuid>ab1b0f52-945d-4fe9-917c-a9d6b010f4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>0d113eb2-107a-4a06-b3ff-c568ec56bd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>624de4a1-eebf-4a28-b3d7-d3701c9b1e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email_ciid' and @type = 'TEXT' and @placeholder = 'name@example.com']</value>
      <webElementGuid>5f5fbaa2-e952-44f9-853a-af1a35936abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
