<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title of Project_title_ciid</name>
   <tag></tag>
   <elementGuidId>f59d5816-f902-480c-bd6f-85f2bc89c8e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b40bc9ad-b7c3-4be2-bde1-24a3a19a13bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_ciid</value>
      <webElementGuid>38c80d7b-6646-4190-bd3e-f24ba4cddc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>9e6c65da-41a3-406d-9893-819adf553240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name of Project</value>
      <webElementGuid>2263d8dc-2a54-4aa4-b497-4b9420824898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_ciid&quot;)</value>
      <webElementGuid>5aed4b67-3786-4b28-b092-b59b12369813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title_ciid']</value>
      <webElementGuid>c6ec01a1-f8cb-4bea-ad8d-6630392abc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>757f417f-262c-4c60-95c1-c174654f46da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>76fa1867-1664-44e6-bf25-be5ec0b2d65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'title_ciid' and @type = 'TEXT' and @placeholder = 'Name of Project']</value>
      <webElementGuid>962f7093-11d5-444f-b88f-eec90b155530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
