<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number_of_consultants_ciid</name>
   <tag></tag>
   <elementGuidId>c0dc63f9-d301-4078-832e-dc032ed663ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number_of_consultants_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number_of_consultants_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>551a05a5-ef5c-42bb-aeaa-f55ae54a4ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_of_consultants_ciid</value>
      <webElementGuid>0d012771-0538-4877-98ba-28ef145868ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>a583d0e8-f027-4421-bc4b-7d07fff152b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>eg. 3</value>
      <webElementGuid>c2e41276-ab11-41e9-aafc-a32ff1a20ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_of_consultants_ciid&quot;)</value>
      <webElementGuid>e481ac9c-e4cf-4a7e-a3e9-a8bc578e8fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number_of_consultants_ciid']</value>
      <webElementGuid>fc81e166-d41a-4a65-9bac-92ae5c40f7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>e3de1df2-08af-4601-b1c3-e66686a6b6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>4959a43f-09ce-4d6a-8506-7cf97588abd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number_of_consultants_ciid' and @type = 'TEXT' and @placeholder = 'eg. 3']</value>
      <webElementGuid>4df956b8-5584-4e4f-9eee-ca24e08416a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
