<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Skills Required_skills_required_auto__a065ba</name>
   <tag></tag>
   <elementGuidId>07c76077-99f1-4f5e-8f2c-60a6df0e58d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skills_required_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='skills_required_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7850bcf-e398-449c-8533-9d674f8e7b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skills_required_ciid</value>
      <webElementGuid>aba2d4a1-e5b7-46fd-9097-cd25604655f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>type here for suggestions</value>
      <webElementGuid>7a3e2af6-d2a2-42b5-b991-d894c6c2ac4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9505c7b2-732a-4efc-916a-8242446a8dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a8e455c-5b2e-4f9b-bd88-c035a659a247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skills_required_auto_suggest_input</value>
      <webElementGuid>96353e41-acd0-4cbb-a40b-c53fce519c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skills_required_ciid&quot;)</value>
      <webElementGuid>4aec574f-1d64-4956-9f49-60b4faae132f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='skills_required_ciid']</value>
      <webElementGuid>eadd4e9d-4e9e-4028-83a5-d34193ab6bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[8]/div/div[2]/div/div/input</value>
      <webElementGuid>eaffc250-c373-4717-bc64-6bd5741a4e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/input</value>
      <webElementGuid>cd6b07b0-25ea-47b0-b0fd-b2fdd82902bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'skills_required_ciid' and @placeholder = 'type here for suggestions' and @type = 'text' and @name = 'skills_required_auto_suggest_input']</value>
      <webElementGuid>c38d6802-cbe8-4c49-91b5-963954876b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
