<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Select-3 - 5 years5 - 8 years8 - 12_d4114c</name>
   <tag></tag>
   <elementGuidId>7574a8f0-fe18-4275-b2c2-1c74036e9dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#years_of_experience_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='years_of_experience_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4dafc6a1-6aaf-4785-9f53-15095802c026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>years_of_experience_ciid</value>
      <webElementGuid>bc1f5fa7-245c-4036-b0dc-2f6cb1f2e84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-3 - 5 years5 - 8 years8 - 12 years12 - 15 years15+ years</value>
      <webElementGuid>1df19eef-c9fe-4086-904a-3de204269d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;years_of_experience_ciid&quot;)</value>
      <webElementGuid>8064b44c-587e-4222-9e63-f10852367e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='years_of_experience_ciid']</value>
      <webElementGuid>41d26cbf-8c0a-4f1b-af3d-2e3c11b49722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[4]/div/div[2]/select</value>
      <webElementGuid>c51fa527-6afa-4dce-8616-82c55bb40eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years of experience'])[1]/following::select[1]</value>
      <webElementGuid>3b5e155b-d00b-4f49-933c-bf20406b7312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>b7989e44-2a6e-4cb7-97dc-7339d44a5950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>1af45cc9-477c-45e6-8952-fbccf28a7e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/select</value>
      <webElementGuid>54e8723e-9170-4913-acfa-ba32e2670ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'years_of_experience_ciid' and (text() = '-Select-3 - 5 years5 - 8 years8 - 12 years12 - 15 years15+ years' or . = '-Select-3 - 5 years5 - 8 years8 - 12 years12 - 15 years15+ years')]</value>
      <webElementGuid>f889613d-3e27-48d8-bdfe-e0c948c9e430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
