<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DaysDaysWeeksMonths</name>
   <tag></tag>
   <elementGuidId>a2a4a50d-cca3-4025-b0ba-b92ef93a0193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unit_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='unit_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf7b9a54-e224-4292-a390-eef9e92448dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unit_ciid</value>
      <webElementGuid>78dc78ff-3c5a-49ff-baae-93b168ef0059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DaysDaysWeeksMonths</value>
      <webElementGuid>a9a90df5-3527-470a-89b9-7bf77788c8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit_ciid&quot;)</value>
      <webElementGuid>f5df0cbd-51bf-4f26-b851-107f9d6da280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='unit_ciid']</value>
      <webElementGuid>554b64bb-1f61-4074-88be-e0dea759fbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[7]/div/div[2]/div/div/div/div/div/div[2]/select</value>
      <webElementGuid>d0104df3-d3a7-44f4-8edb-b64d0792350a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[1]</value>
      <webElementGuid>8866fb2b-39b3-46ea-bbc1-a6f158a90db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part - Time'])[1]/following::select[1]</value>
      <webElementGuid>635de67d-495e-4ba2-9934-e11951808cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skills Required'])[1]/preceding::select[1]</value>
      <webElementGuid>de20267c-4f81-4feb-9e8b-e164d7a8ff57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>8de6c9bd-debb-472b-99d9-d00b23984a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/select</value>
      <webElementGuid>04b0dfe2-7526-4593-9102-c8d9173d221d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'unit_ciid' and (text() = 'DaysDaysWeeksMonths' or . = 'DaysDaysWeeksMonths')]</value>
      <webElementGuid>e48930da-431c-4ddb-b16b-e55736894388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
