<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -RemoteOn-SiteFlexible</name>
   <tag></tag>
   <elementGuidId>3286cc3a-c377-4152-9e37-0fc439899ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='location_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1e6df3c9-4406-4d6b-9ee9-4b19c3362304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location_ciid</value>
      <webElementGuid>287bf0d0-05c7-4eef-82e5-f46a5a01248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -RemoteOn-SiteFlexible</value>
      <webElementGuid>a7462885-eec4-4d32-b7ef-075d4323bf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location_ciid&quot;)</value>
      <webElementGuid>3c5d57f9-54ef-486d-aff0-7e0c71d6e992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='location_ciid']</value>
      <webElementGuid>fe0ea1c6-4bc9-47ac-9520-405cd5d6e960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>d2479b2e-8e4f-4ce8-bf37-87a4a8a4f98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>bfa94141-3a66-4730-a318-733da9e18c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engagement Type'])[1]/preceding::select[1]</value>
      <webElementGuid>fd9016ad-0a7b-4c43-84aa-cd43b60b6c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full - Time'])[1]/preceding::select[1]</value>
      <webElementGuid>726108a1-e1ea-4168-a767-9f9f156d6e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>05699459-a054-4a05-a458-e4607ac28ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'location_ciid' and (text() = '- Select -RemoteOn-SiteFlexible' or . = '- Select -RemoteOn-SiteFlexible')]</value>
      <webElementGuid>18f122a2-985d-431b-a534-a75598e59d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
