<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>c39d4ea5-7512-4596-8336-86ffef7bdbf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div/table/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9e278477-eefd-43cc-bc13-eb841a616300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-cell</value>
      <webElementGuid>76d2410a-8ee4-452b-8094-a1833c2186d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>608c8105-7a2f-4e53-a9d5-94706c4af38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c39237ca-7b2a-4ce7-8a08-fa440782435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbos-app&quot;)/div[1]/div[@class=&quot;base wbos-lang-en&quot;]/div[2]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 cols-lg-8&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;sri-form-fg&quot;]/div[@class=&quot;w-50 vt-input-cont  custom-input-container  empty name_project_start_date type_date&quot;]/div[@class=&quot;ci-wrap&quot;]/div[@class=&quot;ci-input&quot;]/div[1]/div[@class=&quot;date-picker-cont&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/table[@class=&quot;rdp-table&quot;]/tbody[@class=&quot;rdp-tbody&quot;]/tr[@class=&quot;rdp-row&quot;]/td[@class=&quot;rdp-cell&quot;]</value>
      <webElementGuid>e4f0cef5-b003-479c-9593-7ea658973e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div/table/tbody/tr/td[5]</value>
      <webElementGuid>bb6b32e3-2dc3-4ecc-9ac6-055c251a014d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::td[5]</value>
      <webElementGuid>6d770b6a-cc70-49bb-8139-23b0bc905215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::td[5]</value>
      <webElementGuid>51b65696-e107-4769-9483-d5bf05cc164f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project End date'])[1]/preceding::td[31]</value>
      <webElementGuid>54289e67-a15f-4aa8-ab9f-4612b0c06d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/preceding::td[31]</value>
      <webElementGuid>cb692eee-65e5-4607-abad-f6b32ffdd293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>9e1f4b11-72a9-4827-948c-b54234c3f8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1' or . = '1')]</value>
      <webElementGuid>823283ba-86d3-48f4-9db0-73bba1448a94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
