<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_call dring working</name>
   <tag></tag>
   <elementGuidId>d9458c7e-3a0a-47b6-b706-489d41c0f7c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#your_message_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='your_message_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d23e2c90-d7d2-4c61-9ca9-52bdc758dee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>your_message_ciid</value>
      <webElementGuid>43ae0bbe-6d9d-4c69-b1c1-6af47af35042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e34c2a92-3428-4192-af2f-8a2c7aac4cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>suggest preferred time to call or write text here...</value>
      <webElementGuid>553ce78b-d238-4ecc-ac47-0a862d2f57ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>call dring working</value>
      <webElementGuid>60620919-e60d-4bb6-89f3-ab08609de869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;your_message_ciid&quot;)</value>
      <webElementGuid>6a252869-5741-4a39-b8a1-d79d006351ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='your_message_ciid']</value>
      <webElementGuid>13c8065c-7fd1-42e8-896a-ac088f2168c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>f215c47b-e43e-49a6-ada8-fd48d507e254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::textarea[1]</value>
      <webElementGuid>140b8d6d-f898-4d4f-bdb5-d19edead34d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/following::textarea[1]</value>
      <webElementGuid>d1506eb8-da49-4fc6-adc4-8acc739e9a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d8dc45ab-c0b3-42c3-aed2-7790720f1716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8c60b259-ad53-459e-97dc-2ecdcf786efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='call dring working']/parent::*</value>
      <webElementGuid>38ca2f52-3faf-48a8-bb83-c924c5249518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>adcf9f8b-196f-4b74-a395-e758a6b4f1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'your_message_ciid' and @placeholder = 'suggest preferred time to call or write text here...' and (text() = 'call dring working' or . = 'call dring working')]</value>
      <webElementGuid>9b85a728-169a-40cc-bb5a-12481777bddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
