<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Awesome projec</name>
   <tag></tag>
   <elementGuidId>9d36d72e-fe0c-4fe4-b292-e731f032ba9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project_description_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='project_description_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>017e9774-52ef-46c5-9182-b6b3950b56bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project_description_ciid</value>
      <webElementGuid>fd140352-b691-4cd9-98fa-c22a04bb776c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8d76cf4f-5f0a-4003-9f8d-5acc558b811d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write text here ...</value>
      <webElementGuid>45c4c162-6ee7-473c-b800-0e10beffc552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awesome projec</value>
      <webElementGuid>d8fb3f22-2c82-4dc1-b209-58fe839dbd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project_description_ciid&quot;)</value>
      <webElementGuid>ccb33edf-2d3f-4513-85b3-29366d5f6d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='project_description_ciid']</value>
      <webElementGuid>34e997b8-c1d1-4609-90ba-03a015600cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div/div[2]/textarea</value>
      <webElementGuid>350a0489-2e42-42e4-8e0e-21639d5dff85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[1]/following::textarea[1]</value>
      <webElementGuid>c4078eaf-3cb0-4e1a-88b0-451d28f19e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb 13, 2024'])[1]/following::textarea[1]</value>
      <webElementGuid>b335e3c0-f907-490d-8ba6-19eea0ff0567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4597fc99-eaea-4dd7-981f-5e172a26782e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>136dffe2-eb86-4a81-8662-8e1b6738d2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Awesome projec']/parent::*</value>
      <webElementGuid>1a94835b-96c4-48ba-9cc1-419345c60ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0e895af9-8105-4191-ae99-670da954543c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'project_description_ciid' and @placeholder = 'Write text here ...' and (text() = 'Awesome projec' or . = 'Awesome projec')]</value>
      <webElementGuid>07342841-1dcd-4d17-9fd7-35514e0a959a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
