<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_call dring working h</name>
   <tag></tag>
   <elementGuidId>b83a1e28-5d8d-46b2-8c13-d155a47e5795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#your_message_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='your_message_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4bd2603c-ee0f-4b3f-bab5-ef8495638550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>your_message_ciid</value>
      <webElementGuid>75522a81-6264-4ba0-9688-2c94d7d84d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9bcbe6b8-522e-4ced-aa21-e35583d3fa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>suggest preferred time to call or write text here...</value>
      <webElementGuid>00db4aac-14a0-4fb4-b203-7b1dfb565a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>call dring working h</value>
      <webElementGuid>839044ef-431e-4397-abe1-7d486f661c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;your_message_ciid&quot;)</value>
      <webElementGuid>0e4e95a6-d7fd-49bb-96cd-9a4308f3f63d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='your_message_ciid']</value>
      <webElementGuid>8e4e5148-3d3b-4db1-9faf-3a7dae73c0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>4dd4955f-72ee-4efc-9bbd-e5a84c083ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::textarea[1]</value>
      <webElementGuid>7af18a52-d9bf-4b61-9a55-d00ded267af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/following::textarea[1]</value>
      <webElementGuid>3de8b122-7207-490d-b584-705f82a99d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9c890fcb-ec98-4e22-9739-38d534b4f39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3d653cb3-0436-4d6f-9929-e95e3c00deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='call dring working h']/parent::*</value>
      <webElementGuid>641cdae5-aecb-4a96-98ad-dcadf972ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>18117b41-13b2-4af5-8203-2e5407a524e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'your_message_ciid' and @placeholder = 'suggest preferred time to call or write text here...' and (text() = 'call dring working h' or . = 'call dring working h')]</value>
      <webElementGuid>434e5f46-75ab-402e-b7f1-0609c2e286a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
