<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_A</name>
   <tag></tag>
   <elementGuidId>5fa40e82-a349-4af1-b952-4216e52634e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project_description_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='project_description_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>815672f7-5a17-4e93-b517-b9a41ce347bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project_description_ciid</value>
      <webElementGuid>4c0df2df-2332-4345-99c7-92677406246d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>54114666-2cb0-41c8-8cf9-648246c4c42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write text here ...</value>
      <webElementGuid>abf91076-61f2-4ddf-b520-28c65c24a0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>928c9b33-628a-4654-b26a-2221f1a8f9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project_description_ciid&quot;)</value>
      <webElementGuid>dea6b0e1-8d4d-439d-bee2-5eb037483f20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='project_description_ciid']</value>
      <webElementGuid>e3f4b258-f9d1-42a9-85a3-f26554c724e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div/div[2]/textarea</value>
      <webElementGuid>b46c166b-8dbe-4574-9610-318b6d8fcffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[1]/following::textarea[1]</value>
      <webElementGuid>07b690d3-b2c6-460c-9f32-53067bbc61e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb 13, 2024'])[1]/following::textarea[1]</value>
      <webElementGuid>0d785a3a-800c-49d6-ac8d-1970b56ee772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>32a24967-bf06-4a8e-8af5-41d05b8e4ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a8bfb9d2-0034-4b5a-9392-cc4b00fdfc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A']/parent::*</value>
      <webElementGuid>54ce42e1-8a4e-4543-b0fb-50ec276743cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>98d79f9a-64aa-43e2-bd4f-f685114580af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'project_description_ciid' and @placeholder = 'Write text here ...' and (text() = 'A' or . = 'A')]</value>
      <webElementGuid>2a030d8c-e111-48e7-b492-979da149fd6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
