<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ca</name>
   <tag></tag>
   <elementGuidId>05f38b27-5204-4738-9aeb-c5aec120bc5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#your_message_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='your_message_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f7728062-f3d9-4258-96c9-e684ca70dd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>your_message_ciid</value>
      <webElementGuid>17a50630-036b-41ab-8961-9a80a0ad4c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>69fe6ac5-d851-4792-a767-735e236d21ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>suggest preferred time to call or write text here...</value>
      <webElementGuid>46b5523a-b41b-402c-90e1-118558c43c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ca</value>
      <webElementGuid>af61a3a7-ac40-4717-bfda-189cf0ddb567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;your_message_ciid&quot;)</value>
      <webElementGuid>1486c2b4-fd28-4de5-aee0-29c789e7579e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='your_message_ciid']</value>
      <webElementGuid>3c135113-1e8a-4fcb-92b9-0b7be61cf9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>385d2229-26a4-4f43-804c-dc6220263e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::textarea[1]</value>
      <webElementGuid>cdc85c29-9df8-4580-a862-370bc7123290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/following::textarea[1]</value>
      <webElementGuid>3f9ccdd9-ece5-445c-ad0d-875fe3c5382d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4477cba1-77dd-4c74-b4a2-28f47701cbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>68ea667d-f196-425d-8f28-276d4590a829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ca']/parent::*</value>
      <webElementGuid>1abb59ea-d396-4e88-a668-65b0281c250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>381b53fb-49ea-441d-9071-92416ec80df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'your_message_ciid' and @placeholder = 'suggest preferred time to call or write text here...' and (text() = 'ca' or . = 'ca')]</value>
      <webElementGuid>a92b3183-8229-42e7-bbca-30d1047494ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
