<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_call</name>
   <tag></tag>
   <elementGuidId>41607c2a-852c-4cdd-a928-ff0f50f8921a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#your_message_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='your_message_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9e679dec-027f-4332-a9e6-6ea93383005d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>your_message_ciid</value>
      <webElementGuid>c7550bbf-e9f9-4fa5-b955-fe1d620034fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>aabc15a5-66d5-4462-ac81-9e17b7865a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>suggest preferred time to call or write text here...</value>
      <webElementGuid>aa56fdf1-c562-4862-9600-3faafe4c534c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>call</value>
      <webElementGuid>33cc9575-2bd9-465d-81c5-f5a1b26ab94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;your_message_ciid&quot;)</value>
      <webElementGuid>de30c9d3-18a7-43f4-8796-4140308c3910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='your_message_ciid']</value>
      <webElementGuid>3a46e794-66bc-4633-818d-8a8bafba7daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>0c5aa2e4-6d10-461b-8250-cf8e7f8aaf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message'])[1]/following::textarea[1]</value>
      <webElementGuid>dcd54d32-9a66-4bd8-b988-6a7669c66150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/following::textarea[1]</value>
      <webElementGuid>cb470d49-a8af-481b-af79-0239bca1efaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>02d12a10-f182-4daf-bfd9-8ecfc27a7321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d832dcd6-8a2a-4680-95fb-9202b6f1b47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='call']/parent::*</value>
      <webElementGuid>93764a7b-30bc-4a6d-b26a-6b9eaac11989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>aacafb6c-ab01-4db1-85e8-ddce0e0c3cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'your_message_ciid' and @placeholder = 'suggest preferred time to call or write text here...' and (text() = 'call' or . = 'call')]</value>
      <webElementGuid>bc6411ca-5436-4110-9783-56ca571385ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
