<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Awesom</name>
   <tag></tag>
   <elementGuidId>e56985ba-0748-4171-86c0-741cff8c7e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project_description_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='project_description_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>47957f4b-b2ca-438c-a992-845b08686cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project_description_ciid</value>
      <webElementGuid>6698d888-60f1-4c79-9164-7977eefc54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>86de781f-e08c-4b3b-ad0e-f12be1c35fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write text here ...</value>
      <webElementGuid>4ab28d6b-b6c3-4f16-9ed5-e568482e25f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awesom</value>
      <webElementGuid>90c4007b-53aa-472f-b914-b87a7b7e0fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project_description_ciid&quot;)</value>
      <webElementGuid>50d94b7f-6e66-4142-afe5-bc026e31b578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='project_description_ciid']</value>
      <webElementGuid>10158078-d981-4567-b3fd-9a87f4149710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div/div[2]/textarea</value>
      <webElementGuid>6b795f6e-d095-43f4-9e47-ca81f95f7d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[1]/following::textarea[1]</value>
      <webElementGuid>4e3ae709-1d38-459a-b5fa-ed729db2a869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb 13, 2024'])[1]/following::textarea[1]</value>
      <webElementGuid>029d3a4a-ca73-4bfc-b785-67543d14ebf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>88951ca6-0734-4e78-8c00-9a984378924e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>63a9e1da-9616-4969-be75-ad29c5fcde84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Awesom']/parent::*</value>
      <webElementGuid>5a636d86-59ed-4e79-a442-319cb8fce196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3ac58e50-fc74-4eeb-852c-1a8abc3fd377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'project_description_ciid' and @placeholder = 'Write text here ...' and (text() = 'Awesom' or . = 'Awesom')]</value>
      <webElementGuid>31723373-d21c-4945-982e-34e0489bd3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
