<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Awesome pr</name>
   <tag></tag>
   <elementGuidId>fd8214aa-0543-419e-b3bd-d993dfe5ed48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project_description_ciid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='project_description_ciid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4ae60f34-c1b2-456d-b7b1-a8daca26b764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project_description_ciid</value>
      <webElementGuid>751bafe3-d7c1-4e84-8210-ee1332bfea89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c99f441f-8311-4566-ba07-3804e9506779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write text here ...</value>
      <webElementGuid>2cae8dcd-27f6-4ceb-997f-31d774d3b442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awesome pr</value>
      <webElementGuid>7de4bba3-e979-49e9-a956-cccfe4c0bbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project_description_ciid&quot;)</value>
      <webElementGuid>78931f78-fd33-44fb-9cbb-0c381632e6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='project_description_ciid']</value>
      <webElementGuid>348da817-4f25-437c-83a6-458fc32c53d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbos-app']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div/div[2]/textarea</value>
      <webElementGuid>bfd687d5-fccf-4d65-bf1e-50d3b0bc3014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[1]/following::textarea[1]</value>
      <webElementGuid>c074dce0-7da3-4374-bab1-26e8abcbee18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb 13, 2024'])[1]/following::textarea[1]</value>
      <webElementGuid>93e006fd-4086-4548-a003-2dc1c90396aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9327aa77-e26e-48a6-995f-e29e4b578b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>25c5097b-c80f-48d9-a25b-fdcaec4499f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Awesome pr']/parent::*</value>
      <webElementGuid>f7ccfc11-5f50-4f9f-971e-19b4a05d38d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2ce42519-b067-473b-9a9d-6129bc5f566c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'project_description_ciid' and @placeholder = 'Write text here ...' and (text() = 'Awesome pr' or . = 'Awesome pr')]</value>
      <webElementGuid>ccc4d7e8-e4db-4e7d-b6f8-96690f85f36e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
